spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/excle?characterEncoding=utf-8&useSSL=false
    username: root
    password:
mybatis:
  mapper-locations: classpath:mapper/*.xml